config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :cities, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  belongs_to :state
end

app/models/state.rb
# frozen_string_literal: true

class State < ApplicationRecord
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

# Controller for index of cities from search
class CitiesController < ApplicationController

  def index
    puts params
    search = params[:query].capitalize

    @cities = State.where('name LIKE ?', "%#{search}%").first&.cities

    @cities = City.where('name LIKE ?', "%#{search}%") if @cities.nil?

    render 'cities/index'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/index.html.erb
<div> <% @cities.each do |city| %>
  <% result = {cidade: city.name, estado: city.state.name }%>
  <%= result.as_json %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchCities</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <div data-controller="refresh-list">
        <%= form_with url: cities_path, method: :get, html: { class: 'mb-5', data: { refresh_list_target: 'form' } } do |f| %>
          <%= f.text_field :query,
                           class: "form-control",
                           placeholder: 'Digite um cidade/estado',
                           value: params[:query],
                           data: {
                             refresh_list_target: 'searchInput',
                             action: "keyup->refresh-list#update"
                           } %>
        <% end %>
      </div>
    </div>
  </div>
</div>